model_list: 
  - model_name: qwen/qwen3-coder-480b-a35b-instruct-maas
    litellm_params: 
      model: vertex_ai/qwen/qwen3-coder-480b-a35b-instruct-maas
  - model_name: h2loop/h2loop-coder-instruct
    litellm_params: 
      model: vertex_ai/qwen/qwen3-coder-480b-a35b-instruct-maas
  - model_name: moonshotai/kimi-k2-thinking-maas
    litellm_params: 
      model: vertex_ai/moonshotai/kimi-k2-thinking-maas
      vertex_location: "global"
  - model_name: deepseek-ai/deepseek-v3.2-maas
    litellm_params: 
      model: vertex_ai/deepseek-ai/deepseek-v3.2-maas
      vertex_location: "global"
  - model_name: h2loop/coder-mini
    litellm_params: 
      model: vertex_ai/minimaxai/minimax-m2-maas
      vertex_location: "global"
  - model_name: vertex_ai/zai-org/glm-5-maas
    litellm_params: 
      model: vertex_ai/zai-org/glm-5-maas
      vertex_location: "global"
  - model_name: moonshotai/kimi-k2.5
    litellm_params: 
      model: openrouter/moonshotai/kimi-k2.5
      api_key: "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"
  - model_name: minimax/minimax-m2.5
    litellm_params: 
      model: openrouter/minimax/minimax-m2.5
      api_key: "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"

litellm_settings:
  vertex_project: "h2loop-prod"
  vertex_location: "us-south1" # proj location
  # Vertex credentials not required if service account being used is correct in GCR.


