model_list: 
  - model_name: h2loop/h2loop-coder-0-1
    litellm_params: 
      model: vertex_ai/qwen/qwen3-coder-480b-a35b-instruct-maas
      vertex_location: "us-south1" # proj location
  - model_name: h2loop/h2loop-coder-0-1-uav
    litellm_params: 
      model: vertex_ai/qwen/qwen3-coder-480b-a35b-instruct-maas
      vertex_location: "us-south1" # proj location
  - model_name: h2loop/h2loop-coder-0-1-embedded
    litellm_params: 
      model: vertex_ai/qwen/qwen3-coder-480b-a35b-instruct-maas
      vertex_location: "us-south1" # proj location
  - model_name: h2loop/h2loop-coder-ran
    litellm_params: 
      model: vertex_ai/qwen/qwen3-coder-480b-a35b-instruct-maas
      vertex_location: "us-south1" # proj location
      
  # - model_name: h2loop/minimax-m2
  #   litellm_params: 
  #     model: vertex_ai/minimaxai/minimax-m2-maas
  #     vertex_location: "global" # proj location

litellm_settings:
  vertex_project: "h2loop-prod"
  # Vertex credentials not required if service account being used is correct in GCR.


