model_list: 
  - model_name: qwen/qwen3-coder-480b-a35b-instruct-maas
    litellm_params: 
      model: vertex_ai/qwen/qwen3-coder-480b-a35b-instruct-maas
  - model_name: h2loop/h2loop-coder-instruct
    litellm_params: 
      model: vertex_ai/qwen/qwen3-coder-480b-a35b-instruct-maas
  - model_name: kimi/kimi-k2-thinking-maas
    litellm_params: 
      model: vertex_ai/kimi/kimi-k2-thinking-maas

litellm_settings:
  vertex_project: "h2loop-prod"
  vertex_location: "global" # proj location
  # Vertex credentials not required if service account being used is correct in GCR.


