model_list: 
  - model_name: h2loop/h2loop-coder-0-1
    litellm_params: 
      model: vertex_ai/qwen/qwen3-coder-480b-a35b-instruct-maas
  - model_name: h2loop/h2loop-coder-0-1-uav
    litellm_params: 
      model: vertex_ai/qwen/qwen3-coder-480b-a35b-instruct-maas
  - model_name: h2loop/h2loop-coder-0-1-embedded
    litellm_params: 
      model: vertex_ai/qwen/qwen3-coder-480b-a35b-instruct-maas
  - model_name: h2loop/mimimax-m2
    litellm_params: 
      model: vertex_ai/minimaxai/minimax-m2-maas

litellm_settings:
  vertex_project: "h2loop-prod"
  vertex_location: "us-south1" # proj location
  # Vertex credentials not required if service account being used is correct in GCR.


